apiVersion: v1
kind: Service
metadata:
  name: {{.Values.name}}-jmx-service
  namespace: {{.Values.namespace}}
  labels:
    app: {{.Values.name}}
spec:
  type: ClusterIP
  ports:
  - name: httpswls
    port: 7001
    targetPort: 7001
  selector:
    tier: {{.Values.name}}-gui
