# the Harness infrastructure name assigned for this deployment
# the name must match the source control configuration directory for this deployment
# in most cases the name matches the namespace unless there are multiple deployments to the same namespace
name: cnb-ipe
# the Harness namespace setup for this deployment.
namespace: <+infra.namespace>
appType: IPE

image: docker-flume.nexus-dev.onefiserv.net/epp/ipe:<+artifact.tag>

imageRegistryHostname: <+artifact.registryHostname>

imagePullSecret: nexus-image-pull

# host for nfs volume definition
nfsHost: nfs2159.irvsx41001.nas.onefiserv.net
# path for nfs volume definition
nfsPath: /ifs/irvsx41001/nfs/bs/alpha/be/apps/epp-nsf/
# sub path to the gateway directory in the nfs share under nfsPath. For infra.name is replaced with tenant id for deployment to upper environments
nfsGatewaySubPath: gateway/psh/<+infra.name>
nfsDBSubPath: gateway/psh/<+infra.name>/oradata


# the client profile
client: cnb


# database configuration parameters
q5DataSourceURL: "jdbc:oracle:thin:@10.155.144.68:1521/epp_aks_cnb_alpha"
q5DataSourceUser: CNB_IPE_ALPHA
q5DataSourcePassword: secret

# Weblogic trust store JVM options
keyTrustStoreJVMOptions: "-Djavax.net.ssl.keyStore=/u01/oracle/shared/resources/mqm/security/truststore.jks -Djavax.net.ssl.keyStorePassword=redacted -Djavax.net.ssl.trustStore=/u01/oracle/shared/resources/mqm/security/truststore.jks -Djavax.net.ssl.trustStorePassword=redacted"

# NOTE: to stop a deployment change deploy value to false and re-run the Harness pipeline

ipe:
  deploy: true # if set to false the deployment replicas value is set to 0

# deploy MQM pod for testing purposes only
mqm:
  deploy: true


