apiVersion: v1
kind: ConfigMap
metadata:
  name: {{.Values.name}}-configmap
  labels:
    app: {{.Values.name}}
data:
  WL_JVM_OPTIONS: "  -Dweblogic.MaxMessageSize=50000000 -Duser.timezone=America/New_York -Dweblogic.StdoutDebugEnabled=false -Dfile.encoding=UTF8 -Dclient.encoding.override=UTF-8 -Dweblogic.ServerLifeCycleTimeoutVal=210 -Dweblogic.oif.serialFilterMode=disable -XX:+UseParallelGC -XX:+UseParallelOldGC"
