apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{.Values.name}}-ipe
  namespace: {{.Values.namespace}}
spec:
  maxReplicas: 1
  minReplicas: 1
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          averageUtilization: 60
          type: Utilization
    - type: Resource
      resource:
        name: memory
        target:
          averageUtilization: 60
          type: Utilization
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{.Values.name}}-ipe
