---
- name: tasks to get the disk and partition related configuration automatically
  hosts: rhel-mq-servers
  vars_files:
     - vars.yml  
  tasks:
    - block:
      - name: Get addition disk information
        shell: lsblk -b --output NAME,SIZE --bytes | grep -E 'sd[a-z]' | awk '$2 == {{drbdpool_size}}*1024*1024*1024 {print $1}'
        register: addition_disk_info

      - name: Form variable for addition_disk partition
        set_fact:
          add_disk_info: "{{ '/dev/' + addition_disk_info.stdout }}"

      - name: Debug add_disk_info variable
        debug:
          var: add_disk_info          

      - name: Get vg_extra partition name
        shell: "pvscan | awk '/vg_extra/ {print $2}'"
        register: vg_partition_info

      - name: Form variable for vg_extra partition
        set_fact:
          vg_part_info: "{{ vg_partition_info.stdout }}"

      - name: Debug vg_part_info variable
        debug:
          var: vg_part_info

      - name: Get vg_extra partition name
        shell: pvscan | awk '/vg_extra/ {gsub(/[0-9]/,"",$2); print $2}'
        register: vg_partition_name

      - name: Form variable for vg_extra partition name
        set_fact:
          vg_part_name: "{{ vg_partition_name.stdout }}"

      - name: Debug vg_part_name variable
        debug:
          var: vg_part_name

      - name: Get vg_extra partition number
        shell: pvscan | awk '/vg_extra/ {gsub(/[^0-9]/,"",$2); print $2}'
        register: vg_partition_number

      - name: Form variable for vg_extra partition number
        set_fact:
          vg_part_number: "{{ vg_partition_number.stdout }}"

      - name: Debug vg_part_number variable
        debug:
          var: vg_part_number

      become: yes

- name: Playbook to execute roles for MQ
  hosts: rhel-mq-servers
  vars_files:
     - vars.yml
  roles:
      - resize-osdisk-operations
      - mount-operations
      - extra-disk-operations
      - userfile-operations
      - reboot
      - pre-requirements
