# this helm template processes all application configuration files
# and converts them into configmaps or secrets as needed

{{- range $path, $_ :=  .Files.Glob  "{config/**,DPSApp/**,resources/mqm/**,mqm/**}" }}
  {{- if or (contains "protection" $path) (contains "VibesimplejavaLinux" $path) }}
#{{ $path }} generated secret
apiVersion: v1
kind: Secret
metadata:
  name: {{ $.Values.name }}-{{ base $path | lower | replace "." "" }}-secret
type: Opaque
data:
{{ base $path | indent 2 }}: {{ $.Files.Get $path | b64enc }}

---

  {{- else if or (contains "jks" $path) (contains "zip" $path) }}
#{{ $path }} generated binary configMap
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $.Values.name }}-{{ base $path | lower | replace "." "" }}-cm
binaryData:
{{ base $path | indent 2 }}: {{ $.Files.Get $path | b64enc }}

---

  {{- else }}
#{{ $path }} generated standard configMap
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $.Values.name }}-{{ base $path | lower | replace "." "" }}-cm
data:
{{ base $path | indent 2 }}: |-
{{ $.Files.Get $path | indent 4 }}

---
  {{- end }}
{{- end }}