apiVersion: v1
kind: Secret
metadata:
  name: {{.Values.name}}-secret
  labels:
    app: {{.Values.name}}
type: Opaque
data:
  Q5DataSourceUser: {{.Values.q5DataSourceUser | b64enc }}
  Q5DataSourcePassword: {{.Values.q5DataSourcePassword | b64enc }}
  Q5DataSourceIpeUser: {{.Values.q5DataSourceIpeUser | b64enc }}
  Q5DataSourceIpePassword: {{.Values.q5DataSourceIpePassword | b64enc }}
  Q5DataSourceIpeSharedUser: {{.Values.q5DataSourceIpeSharedUser | b64enc }}
  Q5DataSourceIpeSharedPassword: {{.Values.q5DataSourceIpeSharedPassword | b64enc }}

