---
# tasks file for reboot
- name: Check if marker for successful reboot exists in file
  shell: "grep -i 'successful reboot execution' /tmp/fs_status.txt"
  register: reboot_status
  become: yes
  ignore_errors: yes

- block:
    - name: Stop firewall and disable SELinux
      block:
        - name: Reboot the system
          shell: sleep 5 && init 6
          async: 1 
          poll: 0 

        - name: Wait for SSH to become available
          wait_for_connection:
            delay: 60
            timeout: 300
            
    - name: Ping hosts after reboot
      ping:

    - name: Add marker to indicate successful reboot execution
      lineinfile:
        path: /tmp/fs_status.txt
        line: "successful reboot execution"
        create: yes              
  
  become: yes
  when: reboot_status is changed and reboot_status.rc != 0  
