apiVersion: v1
kind: ConfigMap
metadata:
  name: {{.Values.name}}-configmap
  labels:
    app: {{.Values.name}}
data:
  CLIENT: {{.Values.client}}
  JMS_PROVIDER: "MQ"  # can be LOCAL or MQ.
  Q5DataSourceURL: {{.Values.q5DataSourceURL}}
  PSH_CONTEXT_ROOT: "{{ .Values.obfuscatedContextRoot }}/PSH"
  XMS_VALUE: "3g"
  XMX_VALUE: "4g"
{{- if eq true .Values.mqm.deploy }}
  MQ_JVM_OPTIONS: "" #No mqm crypto needed for mqm container.
{{- end }}
