# harness.io/skip-file-for-deploy
apiVersion: apps/v1
kind: Deployment
metadata:
   name: {{.Values.name}}-utility
   namespace: {{.Values.namespace}}
   labels:
      app: {{.Values.name}}
spec:
   selector:
      matchLabels:
        app: {{.Values.name}}
        tier: {{.Values.name}}-utility
   replicas: 0
   progressDeadlineSeconds: 1500 # prevent timeouts in lower environments
   template:
      metadata:
         labels:
            app: {{.Values.name}}
            tier: {{.Values.name}}-utility
         annotations:
            # https://helm.sh/docs/howto/charts_tips_and_tricks/
            rollme: {{ randAlphaNum 5 | quote }} # forces rolling restart from Harness pipelines
      spec:
         serviceAccountName: bank-sa
         imagePullSecrets:
         - name: {{.Values.imagePullSecret}}
         containers:
         -  name: psh
            image: {{.Values.image}}
#            command:
#              - sh
#              - -c
#            args:
#               - while true; do echo -en '\n'; ls /u01/oracle/shared/config -lht ; sleep 1; ls /var/epp-domain-dir/* -lht ; done;
            imagePullPolicy: IfNotPresent
            envFrom:
              - configMapRef:
                  name: {{.Values.name}}-configmap
              - secretRef:
                  name: {{.Values.name}}-secret
            env:
            - name: MY_POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: MY_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            ports:
            - containerPort: 7001
            volumeMounts:
            - name: gatewaydir
              mountPath: /opt/epp/gateway
              subPath: {{.Values.nfsGatewaySubPath}}

         volumes:
         -  name: gatewaydir
            nfs:
              server: {{.Values.nfsHost}}
              path: {{.Values.nfsPath}}
