# tls secret for .btat2.epp.banksol.onefiserv.net domain
apiVersion: v1
kind: Secret
metadata:
  name: {{.Values.name}}-tls-secret
  namespace: {{.Values.namespace}}
data:
  tls.crt: {{ .Files.Get "tls/crt.pem" | b64enc }}
  tls.key: {{ .Files.Get "tls/key.pem" | b64enc }}
type: kubernetes.io/tls