# this helm template processes all application configuration files
# and converts them into configmaps or secrets as needed

{{- range $path, $_ :=  .Files.Glob  "{config/**,DPSApp/**,resources/**,lowers-override/**}" }}
  {{- if or (contains "protection" $path) (contains "VibesimplejavaLinux" $path) }}
#{{ $path }} generated secret
apiVersion: v1
kind: Secret
metadata:
  name: {{ $.Values.name }}-{{ include "name.from.path" $path }}-secret
type: Opaque
data:
{{ base $path | indent 2 }}: {{ $.Files.Get $path | b64enc }}

---

  {{- else if regexMatch "jks|zip|keytab" $path }}
#{{ $path }} generated binary configMap
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $.Values.name }}-{{ include "name.from.path" $path }}-cm
binaryData:
{{ base $path | indent 2 }}: {{ $.Files.Get $path | b64enc }}

---

  {{- else }}
#{{ $path }} generated standard configMap
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $.Values.name }}-{{ include "name.from.path" $path }}-cm
data:
{{ base $path | indent 2 }}: |-
{{ $.Files.Get $path | indent 4 }}

---
  {{- end }}
{{- end }}