apiVersion: v1
kind: Secret
metadata:
  name: {{.Values.name}}-secret
  labels:
    app: {{.Values.name}}
type: Opaque
data:
  Q5DataSourceUser: {{.Values.q5DataSourceUser | b64enc }}
  Q5DataSourcePassword: {{.Values.q5DataSourcePassword | b64enc }}

  KEY_TRUST_STORE_JVM_OPTIONS: {{.Values.keyTrustStoreJVMOptions | b64enc }}